version: "3"

services:
  database:
    container_name: database
    image: mariadb
    volumes:
      - ./data/database:/var/lib/mysql/data
    networks:
      - directus
    ports:
      - "8083:3306"
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: "ctankep00"
      MARIADB_DATABASE: "directus"
      MARIADB_USER: "directus"
      MARIADB_PASSWORD: "directus"

  cache:
    container_name: cache
    image: redis:6
    networks:
      - directus

  directus:
    container_name: api
    image: directus/directus:latest
    ports:
      - 8055:8055
    volumes:
      - ./uploads:/directus/uploads
      - ./extensions:/directus/extensions
    networks:
      - directus
    depends_on:
      - cache
      - database
    environment:
      KEY: "255d861b-5ea1-5996-9aa3-922530ec40b1"
      SECRET: "6116487b-cda1-52c2-b5b5-c8022c45e263"

      DB_CLIENT: "mysql"
      DB_HOST: "database"
      DB_PORT: "3306"
      DB_DATABASE: "directus"
      DB_USER: "directus"
      DB_PASSWORD: "directus"

      CACHE_ENABLED: "true"
      CACHE_STORE: "redis"
      CACHE_REDIS: "redis://cache:6379"

      ADMIN_EMAIL: "jason@minorscience.com"
      ADMIN_PASSWORD: "ctankep00"

networks:
  directus:
